#!/bin/bash
#
#SBATCH --job-name=S1_BIDS_BBX
#SBATCH -N 1
#SBATCH -c 1
#SBATCH -t 2:00:00
#SBATCH -o /projects/niblab/bids_projects/Experiments/bbx/error_files/bids_error_ses-1_%a_out.txt
#SBATCH -e /projects/niblab/bids_projects/Experiments/bbx/error_files/bids_error_ses-1_%a_err.txt



singularity exec -B /:/test /projects/niblab/bids_projects/Singularity_Containers/heudiconv.simg heudiconv \
-b -d /test/projects/niblab/bids_projects/raw_data/continuing_studies/BBx/ses-{session}/{subject}/*dcm \
-s sub-001 sub-002 \
-ss 1 \
-f /test/projects/niblab/bids_projects/Heuristic_Files/bbx_heuristic.py \
-c dcm2niix -o /test/projects/niblab/bids_projects/Experiments/bbx/BIDS/ses-1